name: "Create .env file while ensure the order of envs"
description: "Yet another action to create a .env file with Github Secrets, but allow ordering envs."
author: "Daniel Porto"
branding:
  icon: "file-plus"
  color: "green"
inputs:
  file_name:
    description: "The filename for the envfile"
    default: ".env"
  directory:
    description: "The directory to put the envfile in"
    default: ""
  fail_on_empty:
    description: "Fail if an env key is an empty string"
    default: "false"
runs:
  using: "docker"
  image: "Dockerfile"
